export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const SET_ITEM = 'SET_ITEM'
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST'

export const SET_CART_ITEM = 'SET_CART_ITEM_COUNT'
export const SET_SIMILAR_ITEMS = 'SET_SIMILAR_ITEMS'
export const SET_WISHLIST_FLAG = 'SET_WISHLIST_FLAG'

export const COMMON_ACTION = 'COMMON_ACTION'